name: "PollingPoint"

on:
  push:
    branches:
      - 'main'

env:
  HOSTNAME: ${{ secrets.HOST_NAME }}
  USERNAME: ${{ secrets.USERNAME }}
  SSH_KEY:  ${{ secrets.SSH_PRIVATE_KEY }}


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH Private Key
        run:  echo "$SSH_KEY" > private_key && chmod 600 private_key
      - name: API Deployment
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
          cd /home/ubuntu/projects/api &&
          git pull &&
          cd /home/ubuntu/projects/services &&
          sudo docker compose exec -uroot app sh -c \
          "composer install --optimize-autoloader --no-dev &&
          php artisan config:cache &&
          php artisan optimize &&
          npm run build
          supervisorctl restart all"
          '
